import Head from 'next/head'
import React, { FC } from 'react'

interface HeadParam {
    title: string
}

const HeadHtml: FC<HeadParam> = ({ title }) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default HeadHtml;
